=== ramsay/rpchess/chesswar/Chesswar Specification/RPChess.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="rpchess"
targetNamespace="http://rpchess.googlecode.com/"
elementFormDefault="qualified"
xmlns:rpchess="http://rpchess.googlecode.com/"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:simpleType name ="chesspiece">
    <xs:annotation>
      <xs:documentation>The enum for the base chess piece.</xs:documentation>
    </xs:annotation>
    <xs:restriction base ="xs:string">
      <xs:enumeration value="King"/>
      <xs:enumeration value="Queen"/>
      <xs:enumeration value="Bishop"/>
      <xs:enumeration value="Rook"/>
      <xs:enumeration value="Knight"/>
      <xs:enumeration value="Pawn"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="special">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name"/>
        <!--<xs:element name="author" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="license" type="xs:anyURI"/>-->
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="piece">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="id" type="rpchess:chesspiece"/>
        <xs:element name="max" type="xs:unsignedInt"/>
        <xs:element name="cost" type="xs:int"/>
        <xs:element name="move" type="xs:unsignedInt"/>
        <xs:element name="save" type="xs:int"/>
        <xs:element name="melee" type="xs:int"/>
        <xs:element name="specials">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="rpchess:special" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="license" type="xs:anyURI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="army">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="initiative" type="xs:unsignedInt"/>
        <xs:element name="wealth" type="xs:unsignedInt"/>
        <xs:element name="staff">
          <xs:complexType>
            <xs:sequence>
              <xs:element id="King" ref="rpchess:piece"/>
              <xs:element id="Queen" ref="rpchess:piece"/>
              <xs:element id="Bishop" ref="rpchess:piece"/>
              <xs:element id="Rook" ref="rpchess:piece"/>
              <xs:element id="Knight" ref="rpchess:piece"/>
              <xs:element id="Pawn" ref="rpchess:piece"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
        <xs:element name="license" type="xs:anyURI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="file">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="white" type="xs:boolean"/>
        <xs:element name="index" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="rank">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rpchess:file"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="model">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="whiteroster">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="rpchess:piece"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="blackroster">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="rpchess:piece"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="boardstate">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="rpchess:rank"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="armylist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rpchess:army" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== ramsay/rpchess/RPChess/Chesswar Specification/Armies.xml
<?xml version="1.0" encoding="utf-8"?>
<armylist xmlns="http://rpchess.googlecode.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rpchess.googlecode.com/ RPChess.xsd">
  <army>
    <name>Chaos</name>
    <description>Chaos: the dreadful and evil army of Chaos Lords come from the Chaos Wastes far beyond any civilization. The army includes lots of potent close combat units but is usually few in numbers. Like the army, their foul chaos magic is aimed for destruction and attack, not defense.</description>
    <initiative>4000</initiative>
    <wealth>12</wealth>
    <staff>
      <piece>
        <name>Chaos Lord</name>
        <id>King</id>
        <max>1</max>
        <cost>0</cost>
        <move>2</move>
        <save>2</save>
        <melee>2</melee>
        <specials>
          <special>
            <name>Brave</name>
          </special>
          <special>
            <name>Scary</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Sorcerer</name>
        <id>Queen</id>
        <max>2</max>
        <cost>2</cost>
        <move>2</move>
        <save>3</save>
        <melee>-1</melee>
        <specials>
          <special>
            <name>Contagion</name>
          </special>
          <special>
            <name>Counterspell</name>
          </special>
          <special>
            <name>Dispell</name>
          </special>
          <special>
            <name>Fear</name>
          </special>
          <special>
            <name>Storm</name>
          </special>
          <special>
            <name>Zap!</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Giants</name>
        <id>Rook</id>
        <max>2</max>
        <cost>2</cost>
        <move>2</move>
        <save>2</save>
        <melee>1</melee>
        <specials>
          <special>
            <name>Rocks</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Chaos Bowmen</name>
        <id>Bishop</id>
        <max>4</max>
        <cost>1</cost>
        <move>2</move>
        <save>5</save>
        <melee>0</melee>
        <specials>
          <special>
            <name>Bows(3+)</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Chaos Knights</name>
        <id>Knight</id>
        <max>4</max>
        <cost>2</cost>
        <move>3</move>
        <save>3</save>
        <melee>1</melee>
        <specials>
          <special>
            <name>Assault</name>
          </special>
          <special>
            <name>Brave</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Beastmen</name>
        <id>Pawn</id>
        <max>12</max>
        <cost>1</cost>
        <move>1</move>
        <save>4</save>
        <melee>0</melee>
        <specials>
          <special>
            <name>Plague</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
    </staff>
    <author></author>
    <email></email>
    <license></license>
  </army>
  <army>
    <name>Dwarves</name>
    <description>
      Slow but tough, all dwarf units are heavily armored and powerful in 
      close combat. Their real weakness is in speed as they have no cavalry 
      and all units are very slow because of their small feet.
    </description>
    <initiative>3000</initiative>
    <wealth>12</wealth>
    <staff>
      <piece>
        <name>WarLord</name>
        <id>King</id>
        <max>1</max>
        <cost>0</cost>
        <move>2</move>
        <save>2</save>
        <melee>2</melee>
        <specials>
          <special>
            <name>Brave</name>
          </special>
          <special>
            <name>Crossbows(3+)</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Rune Lord</name>
        <id>Queen</id>
        <max>1</max>
        <cost>3</cost>
        <move>1</move>
        <save>2</save>
        <melee>2</melee>
        <specials>
          <special>
            <name>Brave</name>
          </special>
          <special>
            <name>Crossbows(3+)</name>
          </special>
          <special>
            <name>Counterspell</name>
          </special>
          <special>
            <name>Dispel</name>
          </special>
          <special>
            <name>Protection</name>
          </special>
          <special>
            <name>Storm</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Catapults</name>
        <id>Rook</id>
        <max>4</max>
        <cost>1</cost>
        <move>0</move>
        <save>3</save>
        <melee>0</melee>
        <specials>
          <special>
            <name>Catapults</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Crosbowers</name>
        <id>Bishop</id>
        <max>4</max>
        <cost>1</cost>
        <move>1</move>
        <save>3</save>
        <melee>0</melee>
        <specials>
          <special>
            <name>Crossows(3+)</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name></name>
        <id>Knight</id>
        <max>0</max>
        <cost>0</cost>
        <move>0</move>
        <save>0</save>
        <melee>0</melee>
        <specials/>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Infantry</name>
        <id>Pawn</id>
        <max>12</max>
        <cost>1</cost>
        <move>1</move>
        <save>3</save>
        <melee>1</melee>
        <specials/>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
    </staff>
    <author></author>
    <email></email>
    <license></license>
  </army>
  <army>
    <name>Elfs</name>
    <description>
      From the deep forest come the race of pointy-eared fellows. Unlike other
      armies their basic infantry are all armed with bows, filling the sky 
      with long arrows. And when the enemy army closes, the excellent cavalry 
      and mighty treemen can stop it in tracks.
    </description>
    <initiative>1000</initiative>
    <wealth>18</wealth>
    <staff>
      <piece>
        <name>General</name>
        <id>King</id>
        <max>1</max>
        <cost>0</cost>
        <move>3</move>
        <save>2</save>
        <melee>1</melee>
        <specials>
          <special>
            <name>Brave</name>
          </special>
          <special>
            <name>Assault</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Wizard</name>
        <id>Queen</id>
        <max>2</max>
        <cost>4</cost>
        <move>3</move>
        <save>3</save>
        <melee>-1</melee>
        <specials>
          <special>
            <name>Assault</name>
          </special>
          <special>
            <name>Counterspell</name>
          </special>
          <special>
            <name>Dispell</name>
          </special>
          <special>
            <name>Fear</name>
          </special>
          <special>
            <name>Heal</name>
          </special>
          <special>
            <name>Protection</name>
          </special>
          <special>
            <name>Zap!</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Treemen</name>
        <id>Rook</id>
        <max>2</max>
        <cost>2</cost>
        <move>1</move>
        <save>2</save>
        <melee>1</melee>
        <specials/>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Elite Archers</name>
        <id>Bishop</id>
        <max>4</max>
        <cost>2</cost>
        <move>2</move>
        <save>4</save>
        <melee>0</melee>
        <specials>
          <special>
            <name>Long Bows(2+)</name>
          </special>
        </specials>
        <description></description>
        <author></author>
        <email></email>
        <license></license>
      </piece>
      <piece>
        <name>Cavalry</name>
